export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";
export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_CONFIRM_FAIL = "PASSWORD_RESET_CONFIRM_FAIL";
export const PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_CONFIRM_SUCCESS";
export const GOOGLE_AUTH_SUCCESS = "GOOGLE_AUTH_SUCCESS";
export const GOOGLE_AUTH_FAIL = "GOOGLE_AUTH_FAIL";
export const FACEBOOK_AUTH_SUCCESS = "FACEBOOK_AUTH_SUCCESS";
export const FACEBOOK_AUTH_FAIL = "FACEBOOK_AUTH_FAIL";
export const LOGOUT = "LOGOUT";


export const Fetch_DONOR = "Fetch_DONOR";
export const GRT_USER_PROFILE = "GRT_USER_PROFILE";


export const Fetch_REQUESTS = "Fetch_REQUESTS";
export const CANCEL_REQUESTS = "CANCEL_REQUESTS";

export const FETCH_USER_PROFILE = "FETCH_USER_PROFILE";

export const FETCH_USER_FRIENDS = "FETCH_USER_FRIENDS";

export const FETCH_DONATION_INFO = "FETCH_DONATION_INFO";

export const FETCH_FRIENDS_POSTS = "FETCH_FRIENDS_POSTS";

export const FETCH_USER_POSTS = "FETCH_USER_POSTS";

export const FETCH_COMMENTS = "FETCH_COMMENTS";

